name: Prettier
on:
  push:
    branches: [master, main]

jobs:
  format_front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Prettier with Maven
        run: mvn -f frontend/pom.xml prettier:write

  format_back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Prettier with Maven
        run: mvn -f backend/pom.xml prettier:write
